"""empty message

Revision ID: 0063d6899378
Revises: 05baf1cf1f43
Create Date: 2026-01-31 10:26:11.793598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0063d6899378'
down_revision = '05baf1cf1f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('comment_text',
               existing_type=sa.VARCHAR(length=998),
               type_=sa.String(length=999),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('comment_text',
               existing_type=sa.String(length=999),
               type_=sa.VARCHAR(length=998),
               existing_nullable=False)

    # ### end Alembic commands ###
