"""empty message

Revision ID: 05baf1cf1f43
Revises: 2d2249a4989c
Create Date: 2026-01-30 18:51:37.244982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05baf1cf1f43'
down_revision = '2d2249a4989c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('comment_text',
               existing_type=sa.VARCHAR(length=999),
               type_=sa.String(length=998),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('comment_text',
               existing_type=sa.String(length=998),
               type_=sa.VARCHAR(length=999),
               existing_nullable=False)

    # ### end Alembic commands ###
